services:

  postgres:
    image: postgis/postgis:16-3.4
    container_name: antarctic-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: antarctic_nav
      POSTGRES_USER: antarctic
      POSTGRES_PASSWORD: antarctic_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antarctic -d antarctic_nav"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres_data: